### ISSUE TITLE
Unable to upgrade test forum to development

### ISSUE THREAD

**Issue by KeiroD** [elkarte/Elkarte#2371]
So... hi. :p

When running `~forum/install/upgrade.php`, testing the upgrade path from 1.0.6 to 1.1, because I was going to test the commit that closed #2327,  I get the following error:

```
Warning!
The installer has detected that you already have ElkArte installed. It is strongly advised that you do not try to overwrite an existing installation - continuing with installation may result in the loss or corruption of existing data.
If you have just finished to install your forum and want to use it, please delete the install directory from your server.
 Click here to try to delete the install directory now. (doesn't work on all servers.)
If you wish to upgrade please visit the ElkArte Community Website and download the latest upgrade package.
If you wish to overwrite your existing installation, including all data, it's recommended that you delete the existing database tables and replace Settings.php and try again.
```

... Where's the upgrade file? And why is it not listing the files that need to be checked?

Also, `If you have just finished to install your forum and want to use it, please delete the install directory from your server.` should be corrected to `If you've just finished installing your forum, please delete the install directory.`

Much clearer description, imo.

So as a result, I'm unable to test whether or not the commit that resolves #2327 is properly done.

ETA:

I renamed `install` to something else to see what would throw up an error and of course:

```
Unknown column 'type' in 'where clause'
File: /public_html/forums/sources/subs/Moderation.subs.php
Line: 48
```

So... :P

Also, wtf, I did not realize my database for the forum was still at 1.0.3... I'd upgraded it from 1.0.3 to 1.0.6!

**Comment by emanuele45** [comment]
The first part of the report should be addressed by the commit b83389410e65b1e5eb75ce8a9e3b4a1a64325e13.
The string is changed in 2c77ffc7ef8c7a77ef74b59eafb3d446a6758c68.
Regarding the column error it's "normal" since renaming install will not run upgrade and the column is not added, so it's all good.
Anyway, the easiest way to run the upgrade was to point your browser to forum/install/upgrade.php. ;D

**Comment by KeiroD** [comment]
@emanuele45 

I know how to get to the upgrader... :P But seriously, I'll report back on how the new commit does.

Expect it in a few minutes!

**Comment by emanuele45** [comment]
On the other hand, I was just too lazy to fix the bug when I first realized it was there a while ago. :stuck_out_tongue:

**Comment by emanuele45** [comment]
I merged the code, it should work now (I still have some doubts in certain borderline cases, but... better than nothing. :P

**Comment by KeiroD** [comment]
Still unable to upgrade test forum to latest development:

```
Upgrading Your ElkArte Install!
The upgrader found some old or outdated files.

Please make certain you uploaded the new versions of all the files included in the package. 
Click here to try again.
```

Detection of existing install works as it should, though. It still isn't listing what needs to be checked and upgraded... considering that I basically `mv`'d `Settings.php` up a directory, `rm -rf *` in the test forum directory, then `wget https://github.com/elkarte/Elkarte/archive/development.zip` and `unzip development.zip` before finally `mv`ing the `Settings.php` file back to where it belongs.

Please have the upgrader list the files needing to be checked.

**Comment by emanuele45** [comment]
Sorry, I forgot to mention before: the "some old or outdated files" are... index.php.
As far as I can see the version is correct, so it may be something either in reading the file or the regex extracting the version... :-\
Will take a look.

**Comment by KeiroD** [comment]
Appreciated. :)

I know I'm being hard on you in getting that stuff checked. :P

**Comment by emanuele45** [comment]
With more people like you, I'd have to develop Elk full time! :P

**Comment by emanuele45** [comment]
Unless I missed something that should be fixed.
Otherwise feel free to reopen. ;D
